import React, { useRef } from 'react'
import './ExportPanel.css'

/**
 * Reusable Export Panel for analysis results.
 * Props:
 *   - result: { score, isManipulated, details, fileName, timestamp, hash, sessionId }
 *   - detectorName: string
 */
export default function ExportPanel({ result, detectorName = 'DeepGuard AI' }) {
    const certRef = useRef(null)

    if (!result) return null

    const score = typeof result.score === 'number' ? result.score : parseFloat(result.score) || 0
    const verdict = result.isManipulated ? 'MANIPULATED' : 'AUTHENTIC'
    const ts = result.timestamp || new Date().toISOString()
    const hash = result.hash || Math.random().toString(36).repeat(3).slice(2, 66)
    const sessionId = result.sessionId || `dg-${Date.now().toString(36)}`

    // Build proof text
    const proofText = [
        `═══════════════════════════════════════════`,
        `  DeepGuard AI — Verification Certificate  `,
        `═══════════════════════════════════════════`,
        ``,
        `Detector:     ${detectorName}`,
        `File:         ${result.fileName || 'N/A'}`,
        `Verdict:      ${verdict}`,
        `Score:        ${score.toFixed(1)}%`,
        `Timestamp:    ${ts}`,
        `Session ID:   ${sessionId}`,
        ``,
        `Verification Hash (SHA-256):`,
        `${hash}`,
        ``,
        ...(result.details ? Object.entries(result.details).map(([k, v]) =>
            `${k}: ${typeof v === 'number' ? v.toFixed(1) + '%' : v}`
        ) : []),
        ``,
        `═══════════════════════════════════════════`,
    ].join('\n')

    // Copy to clipboard
    const handleCopy = () => {
        navigator.clipboard.writeText(proofText)
    }

    // Download as PDF (print)
    const handlePDF = () => {
        const printWindow = window.open('', '_blank')
        printWindow.document.write(`
            <html><head><title>DeepGuard Certificate</title>
            <style>
                body { font-family: 'Courier New', monospace; padding: 40px; background: #fff; color: #000; }
                h1 { font-size: 18px; text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; }
                .row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #eee; }
                .verdict { font-size: 24px; text-align: center; margin: 20px 0; font-weight: bold;
                    color: ${result.isManipulated ? '#d32f2f' : '#2e7d32'}; }
                .hash { word-break: break-all; font-size: 11px; background: #f5f5f5; padding: 10px; margin: 10px 0; }
                .footer { text-align: center; font-size: 10px; color: #999; margin-top: 30px; }
            </style></head><body>
            <h1>🛡️ DeepGuard AI — Verification Certificate</h1>
            <div class="verdict">${verdict} — ${score.toFixed(1)}%</div>
            <div class="row"><span>Detector</span><span>${detectorName}</span></div>
            <div class="row"><span>File</span><span>${result.fileName || 'N/A'}</span></div>
            <div class="row"><span>Timestamp</span><span>${new Date(ts).toLocaleString()}</span></div>
            <div class="row"><span>Session ID</span><span>${sessionId}</span></div>
            ${result.details ? Object.entries(result.details).map(([k, v]) =>
            `<div class="row"><span>${k}</span><span>${typeof v === 'number' ? v.toFixed(1) + '%' : v}</span></div>`
        ).join('') : ''}
            <div class="hash"><strong>SHA-256:</strong> ${hash}</div>
            <div class="footer">Generated by DeepGuard AI • Prototype Verification Certificate</div>
            </body></html>
        `)
        printWindow.document.close()
        printWindow.onload = () => { printWindow.print() }
    }

    // Download as PNG
    const handlePNG = () => {
        const canvas = document.createElement('canvas')
        canvas.width = 700
        canvas.height = 500
        const ctx = canvas.getContext('2d')

        // Background
        ctx.fillStyle = '#141414'
        ctx.fillRect(0, 0, 700, 500)

        // Border
        ctx.strokeStyle = '#c5f82a'
        ctx.lineWidth = 2
        ctx.strokeRect(10, 10, 680, 480)

        // Title
        ctx.fillStyle = '#c5f82a'
        ctx.font = 'bold 20px "Courier New"'
        ctx.textAlign = 'center'
        ctx.fillText('🛡️ DeepGuard AI — Verification Certificate', 350, 50)

        // Verdict
        ctx.fillStyle = result.isManipulated ? '#ff6b6b' : '#c5f82a'
        ctx.font = 'bold 28px "Courier New"'
        ctx.fillText(`${verdict}`, 350, 100)

        // Score
        ctx.fillStyle = '#ffffff'
        ctx.font = 'bold 42px "Courier New"'
        ctx.fillText(`${score.toFixed(1)}%`, 350, 155)

        // Details
        ctx.textAlign = 'left'
        ctx.font = '14px "Courier New"'
        ctx.fillStyle = '#a0a0a0'
        let y = 200
        const rows = [
            ['Detector', detectorName],
            ['File', result.fileName || 'N/A'],
            ['Timestamp', new Date(ts).toLocaleString()],
            ['Session ID', sessionId],
        ]
        rows.forEach(([label, val]) => {
            ctx.fillStyle = '#666'
            ctx.fillText(label, 40, y)
            ctx.fillStyle = '#fff'
            ctx.fillText(val, 250, y)
            y += 28
        })

        // Hash
        y += 10
        ctx.fillStyle = '#c5f82a'
        ctx.font = 'bold 12px "Courier New"'
        ctx.fillText('SHA-256 Hash:', 40, y)
        y += 20
        ctx.fillStyle = '#888'
        ctx.font = '11px "Courier New"'
        ctx.fillText(hash.slice(0, 40), 40, y)
        ctx.fillText(hash.slice(40), 40, y + 16)

        // Footer
        ctx.fillStyle = '#444'
        ctx.font = '10px "Courier New"'
        ctx.textAlign = 'center'
        ctx.fillText('Generated by DeepGuard AI • Prototype Verification', 350, 470)

        // Download
        const link = document.createElement('a')
        link.download = `deepguard-cert-${Date.now()}.png`
        link.href = canvas.toDataURL('image/png')
        link.click()
    }

    return (
        <div className="ep">
            <div className="ep__title">Export Results</div>
            <div className="ep__buttons">
                <button className="btn btn-secondary ep__btn" onClick={handlePDF}>
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                        <polyline points="14 2 14 8 20 8" />
                    </svg>
                    PDF Report
                </button>
                <button className="btn btn-secondary ep__btn" onClick={handlePNG}>
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                        <circle cx="8.5" cy="8.5" r="1.5" />
                        <polyline points="21 15 16 10 5 21" />
                    </svg>
                    PNG Certificate
                </button>
                <button className="btn btn-secondary ep__btn" onClick={handleCopy}>
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                        <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                        <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                    </svg>
                    Copy Proof
                </button>
            </div>
        </div>
    )
}
